---
- name: DNSを近いところに差し替え
  register: dns
  replace:
    path: /etc/systemd/resolved.conf
    regexp: "^DNS=.*$"
    replace: "DNS=10.0.0.1 10.16.0.2"
- name: リゾルの再起動
  when: dns is changed
  systemd:
    name: systemd-resolved.service
    state: restarted
